-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Jan 17, 2025 at 07:51 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bookblog`
--

-- --------------------------------------------------------

--
-- Table structure for table `autobiographys`
--

CREATE TABLE `autobiographys` (
  `id` int(11) NOT NULL,
  `author` varchar(50) DEFAULT NULL,
  `author_image` varchar(50) DEFAULT NULL,
  `autobiography` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `autobiographys`
--

INSERT INTO `autobiographys` (`id`, `author`, `author_image`, `autobiography`) VALUES
(1, 'Sabahattin Ali', 'img/Sabahattin Ali/sabahattin-ali.jpg', 'Sabahattin Ali (25 Şubat 1907, Eğridere - 2 Nisan 1948, Kırklareli), Cumhuriyet Döneminde roman, öykü, şiir, oyun gibi türlerde 15\'ten fazla eser kaleme almış, Toplumcu Gerçekçi Türk şair, roman, oyun ve hikaye yazarıdır.Sabahattin Ali, babasının görev yaptığı Bulgaristan’ın Gümülcine sancağına bağlı Eğridere ilçesinde Yüzbaşı Ali Selahattin Bey ve Hüsniye Hanım\'ın ilk çocuğu olarak dünyaya gelmiştir. Fikret ve Süheyla adlarında iki kardeşi vardır. Trabzon kökenli bir aileye mensup olan yazar Sabahattin Ali\'nin büyükbabası Bahriye Alay Emini Oflu Salih Efendi\'dir.Sabahattin Ali, Eğitim hayatına Üsküdar Doğancılar’daki Füyuzat-ı Osmaniye Mektebi’nde başlamıştır. Başarılı bir öğrenci olan Sabahattin Ali, İstanbul Muallim Mektebi’nden öğretmen diploması ile mezun olmuştur.Sabahattin Ali, birçok edebi türde eser vermiş ve eserleri ile Türk edebiyatında öncü isimlerden birisi olmuştur. 1948 tarihinde bir cinayet sonucu öldürülen Sabahattin Ali, birçok dile çevrilen eserleri ile dünyanın birçok ülkesinde tanınmış bir yazardır.'),
(2, 'Orhan Veli Kanık', 'img/Orhan Veli Kanık/orhan-veli-as.jpg', 'Orhan Veli Kanık (1914-1950) İstanbul Beykoz’da dünyaya geldi. Babası Mehmet Veli Bey, Cumhurbaşkanlığı Armoni Orkestrası’nda şefti. Orhan Veli 1925’e kadar Galatasaray Lisesi’nde, ardından Ankara Lisesi’nde (Taş Mektep) öğrenimine devam etti. Edebiyat öğretmenleri Ahmet Hamdi Tanpınar ve Rıfkı Melûl Meriç’in teşvikleriyle yazı ve şiirler yazmaya başladı. Oktay Rifat’la ilkokulda, Melih Cevdet’le lisede tanıştı. 1932’de İstanbul Üniversitesi’nde Felsefe bölümüne başladı. Edebiyat Fakültesi Talebe Cemiyeti Başkanlığı yaptı. Bu sırada Galatasaray Lisesi’nde muallim muaviniydi. Mezun olmadan Ankara PTT Umum Müdürlüğü Telgraf İşleri’nde memurluğa başladı. Tercüme Bürosu’na girdi ve Fransızcadan çeviriler yaptı. 1949’da Yaprak dergisini yayımlamaya başladı. 28 sayı sürdürebildi.\r\n  Orhan Veli Kanık’ın ilk şiirleri 1936’da Varlık dergisinde çıkar. İnsan, Küllük, İnkılâpçı Gençlik, Aile şiirlerinin yayımlandığı dergiler arasındadır. 1941’de Oktay Rifat ve Melih Cevdet’le Garip’i yayımlarlar; kitapta bir de şiir anlayışlarını uzun uzun açıkladıkları Önsöz bulunur. Vazgeçemediğim (1945), Destan Gibi (1946), Yenisi (1947) ve son kitabı Karşı (1949) basılır. La Fontaine’in Masalları (1948) çevirisi ve Nasreddin Hoca Hikâyeleri (1949) ilgi görür. Alfred de Musset, Moliére, Gogol, A.R. Lesage, Charles Lamb, Jean Anouilh, J.P. Sartre ve Turgenyev’den çeviriler yapmıştır.\r\nOrhan Veli Ankara’da, bir gece yarısı belediyenin açtığı çukura düşer, başına aldığı darbe nedeniyle birkaç gün sonra beyin kanaması geçirerek İstanbul’da yaşamını yitirir. Cenazesi büyük bir kalabalığın omuzlarında Beyazıt’tan Sirkeci’ye kadar taşınarak Aşiyan’a defnedilmiştir.'),
(3, 'Oğuz Atay', 'img/Oğuz Atay/oguz-atay.jpg', '\r\nBabası, VI., VII dönem Sinop, VIII. Dönem Kastamonu Milletvekilliği yapan Cemil Atay’dır. 1951′de bugünkü adı Ankara Koleji olan Ankara Maarif Koleji‘ni, 1957′de de İTÜ İnşaat Fakültesi’ni bitirdi. Üç yıl sonra İDMMA İstanbul Devlet Mühendislik ve Mimarlık Akademisi (şimdiki Yıldız Teknik Üniversitesi) İnşaat Bölümü’nde öğretim üyesi oldu. 1975′te doçent olan Atay, Topografya adlı bir de mesleki kitap yazdı. Çeşitli dergi ve gazetelerde makale ve söyleşileri yayınlandı. Oğuz Atay, Tutunamayanlar‘ın 1971-72′de yayınlanmasından sonra, önemli bir tartışmanın odak noktası oldu. Bu romanıyla 1970 TRT Roman Ödülü‘nü kazandı.\r\nTürk edebiyatının en önemli eserlerinden biri olan Tutunamayanlar, eleştirmen Berna Moran tarafından, “hem söyledikleri hem de söyleyiş biçimiyle bir başkaldırı” olarak nitelendirilmiştir. Moran’a göre Tutunamayanlar’daki edebi yetkinlik, Türk romanını çağdaş roman anlayışıyla aynı hizaya getirmiş ve ona çok şey kazandırmıştır.\r\nAtay’ın büyük etki yaratan eseri Tutunamayanlar’ı 1973′te yayınladığı Tehlikeli Oyunlar adlı ikinci romanı izlemiştir. Hikâyelerini Korkuyu Beklerken başlığı altında toplayan Atay, 1911-1967 yılları arasında yaşamış Prof. Mustafa İnan’ın hayatı konu eden Bir Bilim Adamının Romanı‘nı 1975 yılında yayımlamıştır. 1973 yılında yayımlanan Oyunlarla Yaşayanlar adlı oyunu Devlet Tiyatrosu’nda sahnelenmiştir. Atay, beyninde çıkan bir tümör nedeniyle büyük projesi “Türkiye’nin Ruhu“nu yazamadan 13 Aralık 1977′de, İstanbul’da hayatını kaybetmiştir. Edirnekapı Sakızağacı Mezarlığı’na defnedildi.'),
(4, 'Dostoyevski', 'img/Dostoyevski/dostoyevski.jpg', 'us ve dünya edebiyatının en önemli isimlerinden olan Fyodor Mihayloviç Dostoyevski 11 Kasım 1821\'de Moskova’da doğdu. St. Petersburg’da bulunan askeri mühendislik okulunda eğitim gördü. 1846’da yayınlanan İnsancıklar ve hemen ardından kaleme aldığı Beyaz Geceler ile büyük bir edebi başarı elde etti. Çarlık rejiminin baskısına karşı kurulan bir yeraltı örgütüne üyeliği nedeniyle hapse girdi. Sibirya’ya sürgün edilen diğer birçok Rus yazar gibi, o da Rus halkının alt tabakalara mensup simalarıyla geçirdiği bu zamanı edebiyatına taşıdı ve Yeraltından Notlar, Suç ve Ceza, Kumarbaz, Budala, Ecinliler ve Karamazov Kardeşler gibi birbirinden değerli eserler yayınladı. 9 Şubat 1881’de vefat etti. Dostoyevski psikolojik romanın ve felsefi nihilizmin başlıca temsilcisi kabul edilmektedir.'),
(5, 'Nietzche', 'img/Nietzche/nietzche.jpg', 'Friedrich Nietzsche, 15 Ekim 1844 tarihinde Almanya\'da dünyaya geldi.Henüz beş yaşındayken papaz olan babasını kaybetti. Bu durum karşısında oldukça etkilenen Nietzsche, yaklaşık bir sene sonra annesi ve diğer akrabalarıyla birlikte Naumburg\'a yerleşti. Bu olay, düşüncelerini oluşturmasında etkili olmasa da, kişiliğinin oluşumunda oldukça etkilidir. Oldukça çalışkan ve başarılı bir öğrenci olan Nietzsche, küçük yaşta kendi kendine sorular sormaya ve cevaplar aramaya başlıyordu. 13 yaşındayken otobiyografisini yazdı. Kafasında oluşmaya başlayan dini kuşkular, 4 sene sonra yazdığı şiire etki etti. Bir dönem İlahiyat okumak için üniversiteye gitse de, inancını sorgulamaya devam etti. Ailesinden gördüğü dini baskı ve hristiyanlığın cevap veremediği sorular yüzünden, ilerleyen dönemlerde içki içmeye ve ayinlere gitmemeye başladı. O dönemde ateist olduğunu kabul etti ve çevresindekilere de söyledi. Sonraları Arthur Schopenhauer\'in kitabı “İstem ve Tasarım olarak Dünya”yı bulmasıyla bakış açısı tamamen değişti. O yıllarda ünlü filozofun felsefesini derinlemesine inceleyen Nietzsche, yakın çevresine artık \'Schopenhauer\'cu\' olduğunu açıkladı. İlerleyen dönemlerde düşüncelerini yazıya döken ve kitaplaştıran Nietzsche, 1889 senesinde zihinsel çöküş yaşadı. İddiaya göre, caddede yürürken bir atın kırbaçlandığını gördü ve atı korumak için boynuna sarıldı. Sarıldıktan hemen sonra bayıldı ve yere serildi. Hayatının son yıllarını rahatsızlıklarla geçiren ateist filozof Friedrich Wilhelm Nietzsche, 25 Ağustos 1900 tarihinde hayatını kaybetti. ');

-- --------------------------------------------------------

--
-- Table structure for table `books`
--

CREATE TABLE `books` (
  `id` int(11) NOT NULL,
  `title` varchar(50) NOT NULL,
  `author` varchar(50) NOT NULL,
  `genre` varchar(50) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `author_image` varchar(255) DEFAULT NULL,
  `book_image` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `books`
--

INSERT INTO `books` (`id`, `title`, `author`, `genre`, `description`, `author_image`, `book_image`) VALUES
(1, 'Suç ve Ceza', 'Dostoyevski', 'Roman', 'Tüm zamanların en çok konuşulan romanlarından Suç ve Ceza, psikolojik derinliği ve topluma tuttuğu aynayla gündemde kalmaya devam ediyor. St. Petersburg’dan dünyaya yayılan, hatta sınırlarını edebiyatın dışına çıkararak tartışma platformlarına ve sinema festivallerine taşıyan bu yapıt, tekrar tekrar okunmaya ve konuşulmaya değer!Dünyanın en büyük yazarlarından kabul edilen Rus Yazar Fyodor Mihayloviç Dostoyevski’nin 1866’da yayımlanan ölümsüz eseri Suç ve Ceza, tüm insanlığı kavrayan bir öyküye sahip. Aklın, inancın ve eylemlerin vicdan ile muhakemesini tüm çıplaklığıyla yansıtan eser, sizi hem suçlu hem yargıç olduğunuz 705 sayfalık bir soruşturmanın içine çekiyor.', 'img/Dostoyevski/dostoyevski.jpg', 'img/Dostoyevski/sucveceza.jpeg'),
(2, 'Beyaz Geceler', 'Dostoyevski', 'Kurgu', 'Öykünün yalnız ve hayalperest anlatıcısı, Petersburg\'un beyaz gecelerinde sokaklarda dolaşırken Nastenka adında bir genç kızla tanışır. Nastenka da bir o kadar yalnızdır. İkinci buluşmalarında aralarında bir dostluk doğar; Nastenka, ona yaşamöyküsünü anlatır: Âşık olduğu genç adam, bir yıl sonra geri döneceğini söyleyerek Moskova\'ya gitmiş ama aradan bir yıl geçmesine karşın tek bir mektup bile yazmamıştır. Kahramanımız, Nastenka\'yı dinlerken ondan çok etkilenir ama duygularını gizler.\r\nYalnızca XIX. yüzyıl Rus edebiyatının değil, dünya edebiyatının da en büyük yazarlarından Dostoyevski\'nin 27 yaşında yazdığı Beyaz Geceler, okuru sarıp sarmalayan sevecen ve hüzünlü bir uzun öyküdür. Hem dört gece süren bir aşkın hayali hem de bir kişilik parçalanmasının öyküsüdür.', 'img/Dostoyevski/dostoyevski.jpg', 'img/Dostoyevski/beyazgeceler.jpg'),
(3, 'Karamazov Kardeşler', 'Dostoyevski', 'Roman', 'Dostoyevski, yaşamının son yıllarında başyapıtı Karamazov Kardeşler\'i tamamladığında, Rus yazınında felsefe düzeyinde roman-tragedya denen türün de temelini attığının bilincinde değildi. Dostoyevski\'nin yaşam birikiminin tümünü ve sanat gücünün doruğunu içeren bu roman, gerçekte insanı insan yapan ne varsa, onlara adanmış bir destan niteliğini taşır. Yazar, hiçbir romanında \"Karamazov Kardeşler\"de olduğu denli insan ruhuna inmemiş, insanoğlunu bu denli kesitler biçiminde, içgüdülerinin ve istencinin tüm görünümüyle sergilenmiştir. Bir aileyi konu alan ve bir felaketler zinciri olarak gelişen olay örgüsü, bireysel öğelerin yanı sıra, ondokuzuncu yüzyılın ikinci yarısındaki Rus toplumunu da geçirdiği sarsıntıların tümüyle, dünya edebiyatında bir eşi daha bulunmayan bir sanat aynasından yansıtır.', 'img/Dostoyevski/dostoyevski.jpg', 'img/Dostoyevski/karamazovkardesler.webp'),
(4, 'Kumarbaz', 'Dostoyevski', 'Roman', 'Kumarbaz Dostoyevski’nin kendi yaşamından güçlü esintiler taşıyan başyapıtlarından biridir… Dostoyevski, bu romanda eski bir Rus generali ve çevresinin Almanya kumarhanelerinde yaşadığı serüveni anlatır… Borç içinde yüzen general, sevgilisi ve tüm alacaklıları,mirasına konmak için Rusya’daki ‘Yaşlı Kontes’in(Babuşka/ Büyük Anne) ölüm haberini beklemektedirler…‘Yaşlı Kontes’ ise aradan çok geçmeden sapasağlam karşılarına çıkınca işler karışır… Üstelik ‘Babuşka’ büyük bir hevesle rulet masasına oturmuştur… Ve tüm varlığını oyun masasına sürmeye başlar.', 'img/Dostoyevski/dostoyevski.jpg', 'img/Dostoyevski/kumarbaz.webp'),
(5, 'Yeraltından Notlar', 'Dostoyevski', 'Roman', 'İnsan olmak, gerçek insan, etiyle kemiğiyle insan olmak bile ağır gelir bize. Utanırız bundan, insan olmayı yüz karası sayarız, benzeri olmayan toplumsal birtakım insanlar olmak için çabalarız. Ölü doğmuş insanlarız biz ve uzun zamandır canlı babaların çocukları değiliz, giderek daha çok hoşlanıyoruz böyle doğmuş olmaktan. Zevk duyuyoruz bundan. Çok yakın bir gelecekte bir şekilde düşüncelerden doğmanın yolunu bulacağız.\nDostoyevski\'nin Gogol etkisinden kurtularak kendi sesiyle verdiği ilk büyük yapıt olan Yeraltından Notlar, Avrupa\'daki büyük varoluşçu edebiyatı müjdeleyen bir roman. Kitap, okuruna yeraltı diye adlandırdığı bir ruh halinden seslenen karakterin uzun, çılgınca söyleviyle başlıyor. Ardından, bu ahlakçı, uyumsuz, dürüst kişinin yaşadığı bir aşağılanma olayı anlatılıyor. Yüz elli yıldır okunan gerçek bir başyapıt.', 'img/Dostoyevski/dostoyevski.jpg', 'img/Dostoyevski/yeraltındannotlar.jpg'),
(6, 'Düşüş', 'Albert Camus', 'Roman', ' Albert Camus çağdaş düşün ve yazın dünyasındaki saygın yerini yalnızca oyunlarıyla da, yalnızca \"Sisifos Söyleni\" ve \"Başkaldıran İnsan\"la da alırdı belki. Ama Camus\'yü Camus yapan öncelikle anlatı yapıtlarıdır. \"Yabancı\" (1942), \"Veba\" (1947) ve \"Düşüş\"se (1956) bu yapıtlar arasında üç büyük doruktur. Ancak, kimi yazınseverler bu üç başyapıt arasında daha çok \"Düşüş\"ü yeğlerler. Bu kitap, herhangi bir düşünce ya da savı özellikle öne çıkarmaya çalışmadan, yalın bir anlatım ve özgün bir kurgu içinde, zengin bir düşünce duygu yüküyle, çağdaş dünyayı ve insanlarını derinlemesine sorgulayıp yargılar, çirkinliklerini ve düşkünlüklerini sergiler. Ama, aynı zamanda, bu dünyada yaşayan, dolayısıyla şu ya da bu biçimde, şu ya da bu ölçüde onun sorumluluğunu taşıyan bireyler olarak tek tek her birimize bir ayna tutar, eski avukat Jean-Baptiste Clamence\'ın öyküsü aracılığıyla, bize kendini tehlikeye atmadan yaşayanların, yani hepimizin ve her birimizin benzersiz öyküsünü anlatır. \"Düşüş\"ün yayımlanmasından bir yıl sonra Camus\'nün Nobel Ödülünü kazanması bir rastlantı olmasa gerek.', 'img/Albert Camus/albert-camus.jpg', 'img/Albert Camus/düşüş.jpg'),
(7, 'Sisifos Söyleni', 'Albert Camus', 'Felsefe', 'Hayat, uzun ve dolambaçlı yollara sahip, kimi zaman keyifli ama çoğu zaman da yorucu bir yolculuk. Ve bu yolculuğa katılmak ya da katılmamak en başında kimsenin kendi tercihine bırakılmıyor. Peki, kendi kararınız olmadan çıktığınız bu zor yolculuğun sonu nereye varıyor?\n\nYaşam boyunca karşılaşılan tüm güçlükler, hıçkıra hıçkıra ağlamalar, ağız dolusu kahkahalar, elde edilenler ve kaybedilenler… Kısacası tüm çabalar, hayat sona erdiğinde hiç var olmamışçasına yok olup gidiyor. Öyleyse adına hayat denilen bu yolculukta ilerlemeyi sürdürmek, özünde sadece manasız bir çabadan ibaret olabilir mi?\n\nSisifos’un Hikayesini Daha Önce Duymuş Muydunuz?\n\nYunan mitolojisinde adı geçen Sisifos, hilekarlığı ve kurnazlığı ile bilinen bir kral olarak anlatılıyor. Öyle ki, bu yönüyle artık sınırları zorlayan Sisifos, Tanrılar’ı fazlasıyla sinirlendiriyor ve nihayetinde, kendisi henüz bilmese de sonsuza dek sürecek bir cezaya çarptırılıyor.\n\nBir dağın eteğinde koca bir kaya ile baş başa bırakılan Sisifos’un cezası, bu kayayı dağın zirvesine kadar sürüklemek oluyor. Kral uzun uğraşlar sonucunda hedefine ulaşmaya yaklaşsa da kaya her seferinde yeniden aşağıya düşüyor. Bu olay üzerine Sisifos, bu kısır döngünün sonsuza kadar süreceğini anlıyor. Fakat yine de Tanrılar’a meydan okuyarak defalarca kayayı dağın zirvesine doğru ilerletmeye devam ediyor.\n\nTıpkı Hayat Gibi…\n\nAlbert Camus, Yunan mitolojisindeki bu anlatıdan esinlenerek kaleme aldığı Sisifos Söyleni’nde, bu mitolojik olayı hayatla ilişkilendiriyor. Hayat da aynı Sisifos’un hikayesinde olduğu gibi sürekli bitmek tükenmek bilmeyen bir çaba ile devam ediyor. Üstelik bu çabanın sonunda varılacak bir nokta olmadığının da herkes farkında…\n\nYaşam bu kadar boş bir yolculuksa, intihar mantıklı bir çıkış yolu mudur? Okuyucuyu bu soru çevresinde dolaştıran kitap, bakış açısını değiştirerek yaşama dair yeni bir hedef noktası belirliyor. Milyar yıllık dünyada gelmiş geçmiş onca insanın, bu “absürt” denilebilecek çabayı sürdürerek hayatta kalmasının elbette ki bir sebebi olmalı… Bu da hiç şüphesiz ki başkaldırı! Hayata başkaldırmak, intihar etmek değil; tüm bu absürtlüğe inat yaşamayı sürdürebilmektir. Ve mutluluk da ancak ve ancak başkaldırı yoluyla mümkün olacaktır!', 'img/Albert Camus/albert-camus.jpg', 'img/Albert Camus/sisifossöyleni.jpg'),
(8, 'Tersi ve Yüzü', 'Albert Camus', 'Deneme', 'Brice Parain, sık sık, yazdıklarımın en iyisini bu küçük kitabın içerdiğini ileri sürer... Hayır, aldanıyor, çünkü deha bir yana bırakılırsa, insan yirmi iki yaşında yazı yazmasını pek bilemez. Ama Parain\'in söylemek istediğini anlıyorum. Bu acemice sayfalarda, sonradan yazdıklarımdakilerden daha çok gerçek aşk bulunduğunu söylemek istiyor; haksız da değil... Bu sayfaların yazıldığı zamandan beri yaşlandım, çok şeyler görüp geçirdim. Sınırlarımı, sonra hemen hemen bütün zayıflıklarımı tanıyarak kendi hakkımda bilgi edindim... Herkes gibi ben de düşlerim bazı bazı. Ama iki sakin melek onun eşiğinden hiçbir zaman geçirmediler beni; biri dostun yüzünü gösterir, öbürü düşmanın suratını. Evet, bütün bunları biliyorum, aşkın neye patladığını da öğrendim ya da aşağı yukarı. Ama yaşamın kendisi hakkında, Tersi ve Yüzü\'nde acemice söylenenden daha fazlasını bilmiyorum.', 'img/Albert Camus/albert-camus.jpg', 'img/Albert Camus/tersiveyüzü.jpg'),
(9, 'Yabancı', 'Albert Camus', 'Roman', '1942’de yayımlanan Yabancı, romancı, tiyatro yazarı ve düşünür olarak İkinci Dünya Savaşı’ndan sonra yalnız Fransa’da değil tüm dünyada kuşağının sözcüsü ve yol göstericisi olarak kabul edilen Albert Camus’nün, ilk ve en çok ses getiren yapıtıdır. Romanda, işlediği bir suçtan çok, gerçek duygularını dile getirdiği ve toplumun istediği kalıba girmeyi reddettiği için dışlanan bir “yabancı” aracılığıyla, XX. yüzyıl insanının içine düştüğü yabancılaşma anlatılır. Bir türlü ele geçirilemeyen “anlam”ın sürekli aranışını, bilincin toplumdan ve dış dünyadan kopuşunu, topluma yabancı duran kahramanın çevresiyle ve toplumla arasındaki çatışmayı anlatan roman, büyüleyici gücünü arka plandaki derin ve suskun acıdan alır. Camus, genç kahramanı Meursault’nun dış dünyayla arasına koyduğu mesafeyi, kendine ve topluma yabancılaşmasını, annesinin ölümü dahil her şeye nesnel bir biçimde yaklaşmasını büyük bir ustalıkla dile getirir.', 'img/Albert Camus/albert-camus.jpg', 'img/Albert Camus/yabancı.jpg'),
(10, 'Cinsel Seçilim', 'Charles Darwin', 'Bilim', 'Darwin 1859’da yayımladığı Türlerin Kökeni kitabıyla dünyamızın bilim ve kültür tarihini sonsuza kadar değiştirmişti. Ancak bu kitabında henüz çözemediği bazı problemler kalmıştı. İnsanın evrimini ayrıntılarıyla açıklamaktan, biraz da gelecek tepkilerden çekinerek geri durmuştu. 12 yıl konu üzerine yoğun bir şekilde çalıştıktan sonra İnsanın Türeyişi ve Cinsel Seçilim kitabıyla bu açığı kapattı.\n\n“Zaman içinde Darwinci devrim, dünya üzerindeki her eğitimli insanın aklında ve kalbinde emin ve rahat bir şekilde yerini alacaktır, fakat bugün Darwin’in ölümünün üzerinden yüzyıldan fazla zaman geçmesine rağmen hâlâ onun parmak ısırtan çıkarımlarla dolu ifadelerini tam olarak hazmedebilmiş değiliz.”\n–Daniel Dennett, Darwin’in Tehlikeli Fikri\n\n“Darwinci kuram yalnızca üstün bir açıklama gücüne sahip olmakla kalmaz; açıklamasındaki üslubun güç dolu bir zarafeti, dünyanın en unutulmaz başlangıç mitlerine bile üstün gelecek şiirsel bir güzelliği vardır.”\n–Richard Dawkins, Cennetten Akan Irmak\n\n“Darwinci evrim çok derin bir biçimde, kendi varlığımız ve özümüze ilişkin algılarımızda ve bilimin işaret ettiği benzer sorular konusunda da bir devrim yaratmıştır: Biz kimiz? Buraya nasıl geldik? Diğer canlılarla ilişkimiz nedir?”\n–Carl Zimmer, Evrim: Bir Fikrin Başarısı', 'img/Darwin/darwin.jpg', 'img/Darwin/cinselseçilim.jpeg'),
(11, 'İnsanın Türeyişi', 'Charles Darwin', 'Bilim', 'Darwin 1859’da yayımladığı Türlerin Kökeni kitabıyla dünyamızın tarihini sonsuza kadar değiştirmişti. Ancak insanın evrimini ayrıntılarıyla açıklamaktan, biraz da gelecek tepkilerden çekinerek geri durmuştu. 12 yıl konu üzerine yoğun bir şekilde çalıştıktan sonra, ilk basımını 1871 yılında gerçekleştirdiği İnsanın Türeyişi ve Cinsel Seçilim kitabıyla bu açığı kapattı. Elinizdeki bu kitap Darwin’in kitabının ilk bölümünün 1874 tarihli baskısının çevirisidir.\n\nZaman içinde Darwinci devrim, dünya üzerindeki her eğitimli insanın aklında ve kalbinde emin ve rahat bir şekilde yerini alacaktır, fakat bugün Darwin’in ölümünün üzerinden bir asırdan fazla zaman geçmesine rağmen hâlâ onun parmak ısırtan çıkarımlarla dolu ifadelerini tam olarak hazmedebilmiş değiliz.', 'img/Darwin/darwin.jpg', 'img/Darwin/insanıntüreyişi.jpg'),
(12, 'Türlerin Kökeni', 'Charles Darwin', 'Bilim', 'Charles Darwin (1809-1882): Charles Darwin, canlılarda evrimin doğal seçilim yoluyla gerçekleştiğini öne sürdüğü teorisiyle yalnızca döneminin değil daha sonraki ve hatta modern dönemlerin biyoloji bilimini ve genel anlamıyla bilimsel düşünce şeklini devrime uğratmış bir doğa bilginidir. Darwin Türlerin Kökeni kitabında doğal seçilimin yanı sıra “en uyumlu olanın hayatta kalması” ve “ortak kökenden değişerek türeme” gibi kavramları tartışsa da bu fikirleri ve organizmaların evrildiği düşüncesini ilk ortaya atan kişi değildir. Türlerin Kökeni’nin asıl önemi Darwin’in organizmalar arasındaki varyasyona yaptığı vurgu ve bir organizmaya etki eden iç ve dış faktörleri birbirinden ayırmasından kaynaklanır. Yayımlanmasının üzerinden geçen yüz elli yılı aşkın süredir güncelliğini yitirmeyen vurgusuyla ve serinkanlı bilimsel tonuyla Türlerin Kökeni okunması ve kavranması gereken eserlerin başında gelmektedir.', 'img/Darwin/darwin.jpg', 'img/Darwin/türlerinkökeni.jpg'),
(13, 'Böyle Söyledi Zerdüşt', 'Nietzche', 'Felsefe', 'Friedrich Wilhelm Nietzsche (1844-1900): Geleneksel din, ahlak ve felsefe anlayışlarını kendine özgü yoğun ve çarpıcı bir dille eleştiren en etkili çağdaş felsefecilerdendir. Bonn Üniversitesi’nde teoloji okumaya başlayan Nietzsche daha sonra filolojiye yöneldi. Leipzig Üniversitesi’nde öğrenimini sürdürdü, henüz öğrenci iken Basel Üniversitesi filoloji profesörlüğüne aday gösterildi. 1869’da sınav ve tez koşulu aranmadan;yalnızca yazılarına dayanarak doktor unvanı verilen Nietzsche profesörlüğü sırasında klasik filoloji çalışmalarından uzaklaştı ve felsefeyle uğraşmaya başladı. Tragedyanın Doğuşu, Zamana Aykırı Bakışlar, İnsanca Pek İnsanca, Tan Kızıllığı, Şen Bilim, Böyle Söyledi Zerdüşt, İyinin ve Kötünün Ötesinde, Ahlakın Soykütüğü, Ecce Homo, Wagner Olayı, Dionysos Dithyrambosları, Putların Alacakaranlığı, Antichrist, Nietzsche Wagner’e Karşı başlıca büyük eserleri arasında yer almaktadır.', 'img/Nietzche/nietzche.jpg', 'img/Nietzche/böylesöyledizerdüşt.jpg'),
(14, 'Tragedyanın Doğuşu', 'Nietzche', 'Felsefe', 'Friedrich Wilhelm Nietzsche (1844-1900): Geleneksel din, ahlak ve felsefe anlayışlarını kendine özgü yoğun ve çarpıcı bir dille eleştiren en etkili çağdaş felsefecilerdendir. Bonn Üniversitesi’nde teoloji okumaya başlayan Nietzsche daha sonra filolojiye yöneldi. Leipzig Üniversitesi’nde öğrenimini sürdürdü, henüz öğrenci iken Basel Üniversitesi filoloji profesörlüğüne aday gösterildi. 1869’da sınav ve tez koşulu aranmadan, yalnızca yazılarına dayanarak doktor unvanı verilen Nietzsche profesörlüğü sırasında klasik filoloji çalışmalarından uzaklaştı ve felsefeyle uğraşmaya başladı. Tragedyanın Doğuşu; Zamana Aykırı Bakışlar, İnsanca Pek İnsanca, Tan Kızıllığı, Şen Bilim, Böyle Söyledi Zerdüşt, İyinin ve Kötünün Ötesinde, Ahlakın Soykütüğü, Ecce Homo,  Wagner Olayı, Dionysos Dithyrambosları, Putların Batışı, Antichrist, Nietzsche Wagner’e Karşı başlıca büyük eserleri arasında yer almaktadır.', 'img/Nietzche/nietzche.jpg', 'img/Nietzche/böylesöyledizerdüşt.jpg'),
(15, 'Tutunamayanlar', 'Oğuz Atay', 'Roman', 'Türk edebiyatının en önemli eserlerinden biri olan Tutunamayanlar`ı Berna Moran, \"hem söyledikleri hem de söyleyiş biçimiyle bir başkaldırı\" olarak niteler. Moran`a göre \"Oğuz Atay`ın mizah gücü, duyarlılığı ve kullandığı teknik incelikler, Tutunamayanlar`ı büyük bir yeteneğin ürünü yapmış, yapıttaki bu yetkinlik Türk romanını çağdaş roman anlayışıyla aymı hizaya getirmiş ve ona çok şey kazandırmıştır.\" Küçük burjuva dünyasını zekice alaya alan Atay \"saldırısını, tutunanların anlamayacağı, red edeceği türden bir romanla yapar.\"\n\nOğuz Atay, 1934`te İnebolu`da doğdu. Ankara Maarif Koleji`ni, İTÜ İnşaat Fakültesi`ni bitirdi. 1960`ta İDMMA İnşaat Bölümü`nde öğretim üyesi olarak çalışmaya başladı. Tutunamayanlar`ın yayımlanmasının (1971-1972) ardından, önemli bir tartışmanın odağında yeraldı. TRT 1970 Roman Ödülü`nü kazanan Tutunamayanlar`ı kısa bir süre sonra, 1973 yılında Tehlikeli Oyunlar adlı ikinci romanı izledi. Hikayelerini Korkuyu Beklerken başlığı altında topladı. 1911- 1967 arasında yaşamış hocası Prof. Mustafa İnan`ın hayatını romanlaştırarak Bir Bilim Adamının Romanı: Mustafa İnan`ı yazdı. Oyunlarla Yaşayanlar adlı tiyatro eseri Devlet Tiyatroları`nda sahnelendi. Atay 13 Aralık 1977`de, büyük projesi \"Türkiye`nin Ruhu\"nu yazamadan hayata gözlerini yumdu.', 'img/Oğuz Atay/oguz-atay.jpg', 'img/Oğuz Atay/tutunamayanlar.jpg'),
(16, 'Tehlikeli Oyunlar', 'Oğuz Atay', 'Roman', 'Kişinin kendiyle savaşmasını ve yenmesini, kendini dönüştürmesini hayati bir sorun olarak algılamaya çağıran, çarpıcı ve sarsıcı bir roman. Romanın baş kişisi Hikmet Benol, toplumdaki yoğun kargaşanın temelinde yatan gerçekliği araştırırken, gerçeklerle içtenlikle ilgilenmenin toplumu yönetenlerce tehlikeli görüldüğünü seziyor ve `oyun oynuyormuş gibi` ilgilenmenin ve yaşamanın yollarını araştırıyor. Ve hem `tehlikeli` hem de `oyun`la dolu bir yolda gidebileceği son noktaya kadar ilerliyor...', 'img/Oğuz Atay/oguz-atay.jpg', 'img/Oğuz Atay/tehlikelioyunlar.jpg'),
(17, 'Bir Bilim Adamının Romanı', 'Oğuz Atay', 'Roman', 'Türkiye\'de pek benimsenmemiş bir dalda, biyografik roman türünde, Oğuz Atay\'ın kendine özgü üslûbu ve kurgusuyla, kendi hocası da olan Prof. Mustafa Inan\'ı anlatışı. Atay\'ın hedefi, bir halk çocuğunun uluslararası ün sahibi bir bilim adamı oluşunun zorlu macerasını sergilemek. Bunun yanısıra, Oğuz Atay\'ın toplumsal eleştiri kalıplarını zorlayışını da izliyoruz. Elinizdeki kitapta, Prof. Mustafa Inan\'ın hayatından kesitler sunan bir de fotoğraf albümü yeralıyor.', 'img/Oğuz Atay/oguz-atay.jpg', 'img/Oğuz Atay/birbilimadamınınromanı.jpg'),
(18, 'Bütün Şiirleri', 'Orhan Veli Kanık', 'Şiir', 'Orhan Veli: Türk şiirinin \"zincirkıranı\", \"kasketgiydirenı\", \"sivilleştireni\", \"açıkhavaozanı\".\nOrhan Veli çok daha ileriye bir adım attı: Şiirin kendi öz bir dili, bir vezni olmadığı gibi kendine öz konuları da olmayacağını gösterdi, ahengin, musikinin de şiirden kaldırılabileceğini anlattı. (Nurullah Ataç)\nOrhan Veli\'nin kavgası, edebiyatımızın en büyük kavgasıdır, buna inanıyorum. Irmağın yatağını daha doğal bir vadiye indirdi. Şiire kasket giydirdi, sivilleştirdi onu. Bugünkü şiir verimleri onun da verimleridir biraz. (Cemal Süreya)', 'img/Orhan Veli Kanık/orhan-veli-as.jpg', 'img/Orhan Veli Kanık/bütünşiirler.jpg'),
(19, 'Bütün Öyküleri', 'Orhan Veli Kanık', 'Öykü', 'Ne yazayım diye düşünmeye başladım. Acaba hikâye mi yazsam? Hikâyede konunun pek o kadar mühim olmadığını söyleyenler de çıktı. Ama ne olursa olsun, bir vaka lazım. O vakanın bir başı bir sonu olması lazım. Üstelik vaka da, alışılmış bıkılmış vakalardan olmamalı. Küçük burjuvanın hayatını anlatan, onun zaaflarını, onun adiliklerini dünyanın en büyük kahramanlıkları, en asil heyecanları gibi gösteren hikâyelerden illallah dedik artık.Orhan Veli’nin kısa bir hayata sığdırdığı eserleri ebedî bir gençliğin ve tükenmez yaşama sevincinin izlerini taşır. Şiir biçimine ve şiir üzerine düşünmeye getirdiği yenilikçi tavrı, yaşamı kıskıvrak yakalayan gözü ve şiirselliği Orhan Veli’nin düzyazısında da görmek mümkün.Bütün Öyküleri, Orhan Veli’nin öykü türüne getirdiği renklerden oluşan, şairin geniş yelpazesinden izler taşıyan bir kitap.', 'img/Orhan Veli Kanık/orhan-veli-as.jpg', 'img/Orhan Veli Kanık/bütünöyküler.jpg'),
(20, 'Kürk Mantolu Madonna', 'Sabahattin Ali', 'Öykü', 'İlk baskısı 1943 yılında yapılan Kürk Mantolu Madonna, günümüzde halen en çok ilgi gören ve satılan kitaplar arasında bulunuyor. Basıldığı günden bu yana 1 milyondan fazla satan kitap üzerine, birçok araştırma ve inceleme yapılmış, hakkında tezler yazılmış, fakat bu başarısının sırrı tam olarak çözülememiştir. Onu bu kadar özel kılan ve hala konuşuluyor olmasındaki en büyük pay, tabii ki Sabahattin Ali’nin usta kalemi ve başarılı ruh tahlilleridir.', 'img/Sabahattin Ali/sabahattin-ali.jpg', 'img/Sabahattin Ali/kürkmantolumadonna.jpg'),
(21, 'İçimizdeki Şeytan', 'Sabahattin Ali', 'Öykü', '\"İsteyip istemedeğimi doğru dürüst bilmediğim, fakat neticede aleyhime çıkarsa istemediğimi iddia ettiğim bu nevi söz ve fiillerimin daimi bir mesulünü bulmuştum: Buna içimdeki şeytan diyordum, müdafaasını üzerime almaktan korktuğum bütün hareketlerimi ona yüklüyor ve kendi suratıma tüküreceğim yerde, haksızlığa, tesadüfün cilvesine uğramış bir mazlum gibi nefsimi şefkat ve ihtimama layık görüyordum. Halbuki ne şeytanı azizim, ne şeytanı? Bu bizim gururumuzun, salaklığımızın uydurması..\"\n\nBu romanında, toplumsal gündemin kişilikler üzerindeki baskısını ve güçsüz insanın \"kapana kısılmışlığını\" gösteriyor Sabahattin Ali. Aydın geçinenlerin karanlığına, \"insanın içindeki şeytan\"a keskin bir bakış.', 'img/Sabahattin Ali/sabahattin-ali.jpg', 'img/Sabahattin Ali/içimizdekişeytan.jpg'),
(22, 'Kuyucaklı Yusuf', 'Sabahattin Ali', 'Öykü', '\"Bu manasız ve yabancı hayatta bir tek şeye hakikaten sarılmış, hakikaten inanır gibi olmuştu. Bu da karısı idi. Muazzez\'in varlığı Yusuf için büyük boşlukları dolduracak mahiyette bir şey değildi, fakat onun yokluğu müthişti. Onun bu kadar sebepsiz yere, bu kadar insafsızca Yusuf\'un hayatından koparılması çıldırtacak kadar acı idi. Hayatında asıl aradığı şeyin Muazzez olmadığını biliyordu, fakat Muazzez olmadan bunu aramaya muktedir olmayacağını sanıyordu.\"\nKuyucaklı Yusuf Türk edebiyatının belki de en romantik kahramanıdır. Hayatın ve insanların zalimliği karşısındaki naif duruşu ile bir yandan trajik bir sona ilerlerken, bir yandan da yaşadığı lirik aşk hikayesinin kahramanı olarak edebiyat tarihinde yerini almıştır.', 'img/Sabahattin Ali/sabahattin-ali.jpg', 'img/Sabahattin Ali/kuyucaklıyusuf.jpg'),
(23, 'Sırça Köşkü', 'Sabahattin Ali', 'Öykü', 'Niçin hep acı şeyler yazayım? Dostlar, yufka yürekli dostlar bundan hoşlanmıyorlar. \'Hep kötü, sakat şeyleri mi göreceksin?\' diyorlar. \'Hep açlardan, çıplaklardan, dertlilerden mi bahsedeceksin? Geceleri gazete satıp izmarit toplayan serseri çocuklardan; bir kaşık toprak, bir bakraç su için birbirlerini öldürenlerden; cezaevlerinde ruhları kemirile kemirile eriyip gidenlerden; doktor bulamayanlardan; hakkını alamayanlardan başka yazacak şeyler, iyi güzel şeyler kalmadı mı? Niçin yazılarındaki bütün insanların benzi soluk, yüreği kederli? Bu memlekette yüzü gülen, bahtiyar insan yok mu?\'', 'img/Sabahattin Ali/sabahattin-ali.jpg', 'img/Sabahattin Ali/sırçaköşk.jpg'),
(24, 'Anna Karenina', 'Tolstoy', 'Roman', 'Lev Nikolayeviç Tolstoy (1828-1910): Savaş ve Barış, Diriliş ve Kreutzer Sonat’ın büyük yazarı, sadece toplumsal olayları değil, bireyin duygularını da olağanüstü tasvir yeteneğiyle aktarmıştır. Yazar, en ünlü eserlerinden biri olan Anna Karenina’da evlilik, aşk ve ölüm konularını derin bir gözlem gücüyle ele almış, muhteşem edebi dehasıyla işlemiştir. 1875-1877 yılları arasında Ruskiy Vestnik dergisinde tefrika edilen romanın ilk baskısı 1878’de yapılmıştır.\nPek çok yazar ve eleştirmen Anna Karenina’yı gelmiş geçmiş en büyük roman saymaktadır. Tolstoy’un bu büyük eseri birçok kez sinemaya da uyarlanmıştır.', 'img/Tolstoy/tolstoy.jpg', 'img/Tolstoy/annekarenina.jpg'),
(25, 'İnsan Ne ile Yaşar', 'Tolstoy', 'Roman', 'Lev Nikolayeviç Tolstoy (1828-1910): Anna Karenina, Savaş ve Barış, Kreutzer Sonat ve Diriliş’in büyük yazarı, yaşamının son otuz yılında kendini insan, aile, din, devlet, toplum, özgürlük, boyun eğme, başkaldırma, sanat ve estetik konularında kuramsal çalışmalara verdi. Bu dönemde yazdığı öykülerde yıllarca üzerinde düşündüğü insanlık sorunlarını edebi bir kurgu içinde ele aldı. Tolstoy, insan sevgisi ve inanç konularını ustalığının bütün inceliğiyle işlerken, İnsan Neyle Yaşar? ile gerçek hayatı yansıtan tabloların içinde yeni bir ahlak anlayışını ortaya koydu.', 'img/Tolstoy/tolstoy.jpg', 'img/Tolstoy/insanneyleyaşar.webp'),
(26, 'İvan İlyiç\'in Ölümü', 'Tolstoy', 'Roman', '1886 yılında yayınlanan İvan İlyiç’in Ölümü sade, süssüz anlatımıyla Rus gerçekçi edebiyatında eşsiz bir yere sahiptir. Daima gerektiği gibi yaşamaya özen göstermiş bir insanın ölümle yüzleşmesini konu edinen eser, Tolstoy’un yaşamının son döneminde ortaya koyduğu yeni ahlak anlayışının da ilk örneklerinden biridir. İvan İlyiç’in Ölümü Tolstoy’un bir mektubunda belirttiği gibi sıradan bir adamın, sıradan ölümünün kendi gözünden tasviridir.', 'img/Tolstoy/tolstoy.jpg', 'img/Tolstoy/ivanilyiçinölümü.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `poems`
--

CREATE TABLE `poems` (
  `id` int(11) NOT NULL,
  `poem` varchar(255) DEFAULT NULL,
  `author` varchar(30) DEFAULT NULL,
  `author_image` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `poems`
--

INSERT INTO `poems` (`id`, `poem`, `author`, `author_image`) VALUES
(1, 'Akşamüstüne doğru, kış vakti\nBir hasta odasının penceresinde\nYalnız bende değil yalnızlık hali\nDeniz de karanlık, gökyüzü de\nBir acaip, kuşların hali.', 'Orhan Veli Kanık', 'img/Orhan Veli Kanık/orhan-veli-as.jpg'),
(2, 'Ne hoş, ey güzel Tanrım, ne hoş\nMagillerde sefer etmek!\nBir sahilden çözülüp gitmek\nDüşünceler gibi başıboş.', 'Orhan Veli Kanık', 'img/Orhan Veli Kanık/orhan-veli-as.jpg'),
(3, 'Bekliyorum\r\nÖyle bir havada gel ki,\r\nvazgeçmek mümkün olmasın!', 'Orhan Veli Kanık', 'img/Orhan Veli Kanık/orhan-veli-as.jpg'),
(4, 'Bakakalırım giden geminin ardından;\r\nAtamam kendimi denize, dünya güzel;\r\nSerde erkeklik var, ağlayamam.', 'Orhan Veli Kanık', 'img/Orhan Veli Kanık/orhan-veli-as.jpg'),
(5, 'Her gün bu kadar güzel mi bu deniz?\nBöyle mi görünür gökyüzü her zaman?\nHer zaman güzel mi bu kadar,\nBu eşya, bu pencere?\nDeğil,\nVallahi değil;\nBir iş var bu işin içinde. ', 'Orhan Veli Kanık', 'img/Orhan Veli Kanık/orhan-veli-as.jpg'),
(6, 'Her gün bu kadar güzel mi bu deniz?\r\nBöyle mi görünür gökyüzü her zaman?\r\nHer zaman güzel mi bu kadar,\r\nBu eşya, bu pencere?\r\nDeğil,\r\nVallahi değil;\r\nBir iş var bu işin içinde. ', 'Orhan Veli Kanık', 'img/Orhan Veli Kanık/orhan-veli-as.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `autobiographys`
--
ALTER TABLE `autobiographys`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `books`
--
ALTER TABLE `books`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `poems`
--
ALTER TABLE `poems`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `autobiographys`
--
ALTER TABLE `autobiographys`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT for table `books`
--
ALTER TABLE `books`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=27;

--
-- AUTO_INCREMENT for table `poems`
--
ALTER TABLE `poems`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
